export const moviesResponse = {
  docs: [
    {
      _id: '5cd95395de30eff6ebccde56',
      name: 'The Lord of the Rings Series',
      runtimeInMinutes: 558,
      budgetInMillions: 281,
      boxOfficeRevenueInMillions: 2917,
      academyAwardNominations: 30,
      academyAwardWins: 17,
      rottenTomatoesScore: 94,
    },
    {
      _id: '5cd95395de30eff6ebccde57',
      name: 'The Hobbit Series',
      runtimeInMinutes: 462,
      budgetInMillions: 675,
      boxOfficeRevenueInMillions: 2932,
      academyAwardNominations: 7,
      academyAwardWins: 1,
      rottenTomatoesScore: 66.33333333,
    },
    {
      _id: '5cd95395de30eff6ebccde58',
      name: 'The Unexpected Journey',
      runtimeInMinutes: 169,
      budgetInMillions: 200,
      boxOfficeRevenueInMillions: 1021,
      academyAwardNominations: 3,
      academyAwardWins: 1,
      rottenTomatoesScore: 64,
    },
    {
      _id: '5cd95395de30eff6ebccde59',
      name: 'The Desolation of Smaug',
      runtimeInMinutes: 161,
      budgetInMillions: 217,
      boxOfficeRevenueInMillions: 958.4,
      academyAwardNominations: 3,
      academyAwardWins: 0,
      rottenTomatoesScore: 75,
    },
    {
      _id: '5cd95395de30eff6ebccde5a',
      name: 'The Battle of the Five Armies',
      runtimeInMinutes: 144,
      budgetInMillions: 250,
      boxOfficeRevenueInMillions: 956,
      academyAwardNominations: 1,
      academyAwardWins: 0,
      rottenTomatoesScore: 60,
    },
    {
      _id: '5cd95395de30eff6ebccde5b',
      name: 'The Two Towers ',
      runtimeInMinutes: 179,
      budgetInMillions: 94,
      boxOfficeRevenueInMillions: 926,
      academyAwardNominations: 6,
      academyAwardWins: 2,
      rottenTomatoesScore: 96,
    },
    {
      _id: '5cd95395de30eff6ebccde5c',
      name: 'The Fellowship of the Ring',
      runtimeInMinutes: 178,
      budgetInMillions: 93,
      boxOfficeRevenueInMillions: 871.5,
      academyAwardNominations: 13,
      academyAwardWins: 4,
      rottenTomatoesScore: 91,
    },
    {
      _id: '5cd95395de30eff6ebccde5d',
      name: 'The Return of the King',
      runtimeInMinutes: 201,
      budgetInMillions: 94,
      boxOfficeRevenueInMillions: 1120,
      academyAwardNominations: 11,
      academyAwardWins: 11,
      rottenTomatoesScore: 95,
    },
  ],
  total: 8,
  limit: 20,
  offset: 0,
  page: 1,
  pages: 1,
};
export const oneMovieResponse = {
  docs: [
    {
      _id: '5cd95395de30eff6ebccde58',
      name: 'The Unexpected Journey',
      runtimeInMinutes: 169,
      budgetInMillions: 200,
      boxOfficeRevenueInMillions: 1021,
      academyAwardNominations: 3,
      academyAwardWins: 1,
      rottenTomatoesScore: 64,
    },
  ],
  total: 1,
  limit: 20,
  offset: 0,
  page: 1,
  pages: 1,
};
export const zeroMovieResponse = {
  docs: [],
  total: 1,
  limit: 20,
  offset: 0,
  page: 1,
  pages: 1,
};
export const allBooks = {
  docs: [
    {
      name: 'The Fellowship Of The Ring',
      _id: '5cf5805fb53e011a64671582',
    },
    {
      name: 'The Two Towers',
      _id: '5cf58077b53e011a64671583',
    },
    {
      name: 'The Return Of The King',
      _id: '5cf58080b53e011a64671584',
    },
  ],
  total: 3,
  limit: 20,
  offset: 0,
  page: 1,
  pages: 1,
};
export const moviesSortedByBudget = {
  docs: [
    {
      _id: '5cd95395de30eff6ebccde5c',
      name: 'The Fellowship of the Ring',
      runtimeInMinutes: 178,
      budgetInMillions: 93,
      boxOfficeRevenueInMillions: 871.5,
      academyAwardNominations: 13,
      academyAwardWins: 4,
      rottenTomatoesScore: 91,
    },
    {
      _id: '5cd95395de30eff6ebccde5b',
      name: 'The Two Towers ',
      runtimeInMinutes: 179,
      budgetInMillions: 94,
      boxOfficeRevenueInMillions: 926,
      academyAwardNominations: 6,
      academyAwardWins: 2,
      rottenTomatoesScore: 96,
    },
    {
      _id: '5cd95395de30eff6ebccde5d',
      name: 'The Return of the King',
      runtimeInMinutes: 201,
      budgetInMillions: 94,
      boxOfficeRevenueInMillions: 1120,
      academyAwardNominations: 11,
      academyAwardWins: 11,
      rottenTomatoesScore: 95,
    },
    {
      _id: '5cd95395de30eff6ebccde58',
      name: 'The Unexpected Journey',
      runtimeInMinutes: 169,
      budgetInMillions: 200,
      boxOfficeRevenueInMillions: 1021,
      academyAwardNominations: 3,
      academyAwardWins: 1,
      rottenTomatoesScore: 64,
    },
    {
      _id: '5cd95395de30eff6ebccde59',
      name: 'The Desolation of Smaug',
      runtimeInMinutes: 161,
      budgetInMillions: 217,
      boxOfficeRevenueInMillions: 958.4,
      academyAwardNominations: 3,
      academyAwardWins: 0,
      rottenTomatoesScore: 75,
    },
    {
      _id: '5cd95395de30eff6ebccde5a',
      name: 'The Battle of the Five Armies',
      runtimeInMinutes: 144,
      budgetInMillions: 250,
      boxOfficeRevenueInMillions: 956,
      academyAwardNominations: 1,
      academyAwardWins: 0,
      rottenTomatoesScore: 60,
    },
    {
      _id: '5cd95395de30eff6ebccde56',
      name: 'The Lord of the Rings Series',
      runtimeInMinutes: 558,
      budgetInMillions: 281,
      boxOfficeRevenueInMillions: 2917,
      academyAwardNominations: 30,
      academyAwardWins: 17,
      rottenTomatoesScore: 94,
    },
    {
      _id: '5cd95395de30eff6ebccde57',
      name: 'The Hobbit Series',
      runtimeInMinutes: 462,
      budgetInMillions: 675,
      boxOfficeRevenueInMillions: 2932,
      academyAwardNominations: 7,
      academyAwardWins: 1,
      rottenTomatoesScore: 66.33333333,
    },
  ],
  total: 8,
  limit: 10,
  offset: 0,
  page: 1,
  pages: 1,
};
export const twentyCharactersFromPage2 = {
  docs: [
    {
      _id: '5cd99d4bde30eff6ebccfbc6',
      height: '',
      race: 'Human',
      gender: 'Female',
      birth: 'Between ,SA 700, and ,SA 750',
      spouse: '',
      death: 'Early ,Second Age',
      realm: '',
      hair: '',
      name: 'Almiel',
      wikiUrl: 'http://lotr.wikia.com//wiki/Almiel',
    },
    {
      _id: '5cd99d4bde30eff6ebccfbc7',
      height: '',
      race: 'Human',
      gender: 'Male',
      birth: 'TA 3017',
      spouse: '',
      death: 'FO 95',
      realm: '',
      hair: '',
      name: 'Alphros',
      wikiUrl: 'http://lotr.wikia.com//wiki/Alphros',
    },
    {
      _id: '5cd99d4bde30eff6ebccfbc9',
      height: '',
      race: 'Human',
      gender: 'Male',
      birth: 'Late ,Second Age',
      spouse: 'Unnamed wife',
      death: 'Sailed West either SA 3310 fate unknown',
      realm: '',
      hair: '',
      name: 'Amandil',
      wikiUrl: 'http://lotr.wikia.com//wiki/Amandil',
    },
    {
      _id: '5cd99d4bde30eff6ebccfc63',
      height: '',
      race: 'Hobbit',
      gender: 'Female',
      birth: 'TA 2904',
      spouse: 'None',
      death: 'TA 2998',
      realm: '',
      hair: '',
      name: 'Amaranth Brandybuck',
      wikiUrl: 'http://lotr.wikia.com//wiki/Amaranth_Brandybuck',
    },
    {
      _id: '5cd99d4bde30eff6ebccfbca',
      height: '',
      race: 'Elf',
      gender: 'Female',
      birth: 'YT',
      spouse: 'Loved ,Finrod, but it is unknown whether they married',
      death: 'Still alive',
      realm: '',
      hair: '',
      name: 'Amarië',
      wikiUrl: 'http://lotr.wikia.com//wiki/Amari%C3%AB',
    },
    {
      _id: '5cd99d4bde30eff6ebccfbd7',
      height: '',
      race: 'Elf',
      gender: 'Male',
      birth: 'Sometime during ,Years of the Trees, or the ,First Age',
      spouse: 'Unnamed wife',
      death: 'SA 3434',
      realm: 'Lórien',
      hair: '',
      name: 'Amdír',
      wikiUrl: 'http://lotr.wikia.com//wiki/Amd%C3%ADr',
    },
    {
      _id: '5cdbdecb6dc0baeae48cfada',
      death: 'NaN',
      birth: 'NaN',
      hair: 'NaN',
      realm: 'NaN',
      height: 'NaN',
      spouse: 'NaN',
      gender: 'NaN',
      name: 'Amlach',
      race: 'NaN',
    },
    {
      _id: '5cd99d4bde30eff6ebccfbcd',
      height: '',
      race: 'Human',
      gender: 'Male',
      birth: 'TA 726',
      spouse: 'Unnamed wife',
      death: 'TA 946',
      realm: 'Arthedain',
      hair: '',
      name: 'Amlaith',
      wikiUrl: 'http://lotr.wikia.com//wiki/Amlaith',
    },
    {
      _id: '5cd99d4bde30eff6ebccfbd5',
      height: '',
      race: 'Elf',
      gender: 'Male',
      birth: 'Years of the Trees',
      spouse: 'None',
      death: 'FA 538',
      realm: 'Estolad',
      hair: 'Dark red',
      name: 'Amras',
      wikiUrl: 'http://lotr.wikia.com//wiki/Amras',
    },
    {
      _id: '5cd99d4bde30eff6ebccfbd8',
      height: '',
      race: 'Elf',
      gender: 'Male',
      birth: 'Years of the Trees',
      spouse: 'None',
      death: 'YT 1497 ,Losgar',
      realm: '',
      hair: 'Dark red',
      name: 'Amrod',
      wikiUrl: 'http://lotr.wikia.com//wiki/Amrod',
    },
    {
      _id: '5cd99d4bde30eff6ebccfbce',
      height: '',
      race: 'Elf',
      gender: 'Male',
      birth: '',
      spouse: 'Nimrodel',
      death: 'TA 1981',
      realm: 'Lórien',
      hair: 'Golden',
      name: 'Amroth',
      wikiUrl: 'http://lotr.wikia.com//wiki/Amroth',
    },
    {
      _id: '5cd99d4bde30eff6ebccfbcf',
      height: '',
      race: 'Human',
      gender: 'Male',
      birth: 'TA 2994',
      spouse: '',
      death: '',
      realm: '',
      hair: '',
      name: 'Amrothos',
      wikiUrl: 'http://lotr.wikia.com//wiki/Amrothos',
    },
    {
      _id: '5cd99d4bde30eff6ebccfbd0',
      height: '',
      race: 'Elf',
      gender: 'Female',
      birth: 'YT',
      spouse: 'Fingolfin',
      death: '',
      realm: '',
      hair: '',
      name: 'Anairë',
      wikiUrl: 'http://lotr.wikia.com//wiki/Anair%C3%AB',
    },
    {
      _id: '5cd99d4bde30eff6ebccfbd1',
      height: '',
      race: 'Human',
      gender: 'Male',
      birth: 'TA 136',
      spouse: 'Unnamed wife',
      death: 'TA 411',
      realm: 'Gondor',
      hair: '',
      name: 'Anardil',
      wikiUrl: 'http://lotr.wikia.com//wiki/Anardil',
    },
    {
      _id: '5cd99d4bde30eff6ebccfbd2',
      height: '',
      race: 'Human',
      gender: 'Male',
      birth: 'Late ,Third Age',
      spouse: '',
      death: '',
      realm: '',
      hair: 'Dark',
      name: 'Anborn',
      wikiUrl: 'http://lotr.wikia.com//wiki/Anborn',
    },
    {
      _id: '5cdbdecb6dc0baeae48cfad8',
      death: 'FA 587',
      birth: 'Possibly before the Creation of Arda',
      hair: 'NaN',
      realm: 'NaN',
      height: 'As tall as a mountain',
      spouse: 'NaN',
      gender: 'Male',
      name: 'Ancalagon',
      race: 'Dragons',
    },
    {
      _id: '5cd99d4bde30eff6ebccfbd3',
      height: '',
      race: 'Human',
      gender: 'Female',
      birth: 'FA 361',
      spouse: 'Loved ,Aegnor, but they never married',
      death: 'FA 455',
      realm: '',
      hair: 'Dark brown',
      name: 'Andreth',
      wikiUrl: 'http://lotr.wikia.com//wiki/Andreth',
    },
    {
      _id: '5cd99d4bde30eff6ebccfbd4',
      height: '',
      race: 'Human',
      gender: 'Male',
      birth: 'FA 440',
      spouse: 'Unnamed wife',
      death: 'FA 489',
      realm: '',
      hair: '',
      name: 'Andróg',
      wikiUrl: 'http://lotr.wikia.com//wiki/Andr%C3%B3g',
    },
    {
      _id: '5cdbdecb6dc0baeae48cfad9',
      death: 'NaN',
      birth: 'NaN',
      hair: 'NaN',
      realm: 'NaN',
      height: 'NaN',
      spouse: 'NaN',
      gender: 'NaN',
      name: 'Andvír',
      race: 'NaN',
    },
    {
      _id: '5cdbdecb6dc0baeae48cfa4d',
      death: 'NaN',
      birth: 'NaN',
      hair: 'NaN',
      realm: 'NaN',
      height: 'NaN',
      spouse: 'NaN',
      gender: 'NaN',
      name: 'Andwise Roper',
      race: 'NaN',
    },
  ],
  total: 20,
  limit: 20,
  offset: 1,
  page: 2,
  pages: 47,
};
